name = "Slugify"
uuid = "6a57dadc-0402-4d39-bf46-19b28e03609d"
authors = ["Chayan Datta"]
version = "1.0.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1"
JSON = "0.21"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
